#!/bin/bash

# echo $(pwd)

new () {
# ansible-galaxy list |grep rjayroach.prepd_cli
# if exit code is 1 then
# ansible-galaxy install rjayroach.prepd_cli


cat <<'EOF' > ansible.cfg
[defaults]
inventory = hosts
stdout_callback=actionable
# gathering = explicit
retry_files_enabled = no
EOF

cat <<'EOF' > hosts
prepd ansible_connection=local
EOF

cat <<'EOF' > prepd.yml
#!/usr/bin/env ansible-playbook
---
- hosts: prepd
  roles: [prepd-cli/runner]
EOF

chmod +x prepd.yml

./prepd.yml "-e user_action=new -e project_dir=$1"

rm ansible.cfg hosts prepd.yml

# mv roles $1

}


if [ "$1" == "new" ]; then
  if [ -f ansible.cfg ] || [ -f prepd.yml ]; then
    echo "Cannot create inside an existing project"
    exit 1
  else
    new "$2"
  fi
elif [ ! -f ansible.cfg ] || [ ! -f prepd.yml ]; then
  echo "Not a prped project"
  exit 1
else
  str="./prepd.yml"
  cnt=0
  for i in "$@"; do
    if [ "$cnt" == 0 ]; then
      str="$str -e user_action=$i"
    else
      str="$str -e arg_$cnt=$i"
    fi
    cnt=$((cnt + 1))
  done
  echo ${str# }
  ${str# }
fi
